name: test

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-repos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup-go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b

      - name: run-tests
        run: |
          go test -v
