name: build-test-deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-repos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup-go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b

      - name: run-tests
        run: |
          go test -v

  build-docs:
    needs: test
    runs-on: ubuntu-latest
    env:
      FEEDS: ${{vars.FEEDS}}
    steps:
      - name: setup-repos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup-go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b

      - name: setup-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065

      - name: setup mkdocs
        run: pip install mkdocs

      - name: build-docs
        run: mkdocs build

      - name: build-demos
        run: |
          mkdir site/demo/
          echo $FEEDS | go run . -o site/demo/index.html
          echo $FEEDS | go run . -o site/demo/solarized.html -s /styles/solarized.css
          echo $FEEDS | go run . -o site/demo/lobster.html -s /styles/lobster.css
          echo $FEEDS | go run . -o site/demo/hackernews.html -s /styles/hackernews.css

      - name: upload-artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    needs: build-docs
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
