name: test-build-and-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-repos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup-go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b

      - name: run-tests
        run: |
          go test -v

  build-and-release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: setup-repos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup-go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b

      - name: cross-platform-build
        run: |
          mkdir ./builds/
          GO_LDFLAGS="-s -w" # strip debug info
          GOARCH=arm64
          GOOS=linux   go build -o ./builds/tinyfeed_linux_arm64
          GOOS=freebsd go build -o ./builds/tinyfeed_freebsd_arm64
          GOOS=darwin  go build -o ./builds/tinyfeed_darwin_arm64
          GOOS=windows go build -o ./builds/tinyfeed_windows_arm64
          GOARCH=amd64
          GOOS=linux   go build -o ./builds/tinyfeed_linux_amd64
          GOOS=freebsd go build -o ./builds/tinyfeed_freebsd_amd64
          GOOS=darwin  go build -o ./builds/tinyfeed_darwin_amd64
          GOOS=windows go build -o ./builds/tinyfeed_windows_amd64

          apt install upx
          upx ./builds/tinyfeed_linux*
          upx ./builds/tinyfeed_windows*

      - name: release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174
        with:
          artifacts: "./builds/*"
